[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.8"
package_manager = "pnpm"

[features]
seeds = false
resolution = true
skip-lint = false

[programs.localnet]
fogo_onre_relayer = "onrenRKgX54qtWeK3cuaTBE71xx7dWMXn82ubH61vAp"

[programs.devnet]
fogo_onre_relayer = "onrenRKgX54qtWeK3cuaTBE71xx7dWMXn82ubH61vAp"

[programs.mainnet]
fogo_onre_relayer = "onrenRKgX54qtWeK3cuaTBE71xx7dWMXn82ubH61vAp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
# wallet = ".keys/authority.json"

[scripts]
test = "pnpm test"

[test]
startup_wait = 1000
