[toolchain]
anchor_version = "1.0.0"
solana_version = "3.1.8"
package_manager = "pnpm"

[features]
seeds = false
resolution = true
skip-lint = false

[programs.localnet]
relayer = "Re1ayRHhmeqByGjgT5uLFExZCvQ8sv6LK74xowK8pJH"

[programs.devnet]
relayer = "Re1ayRHhmeqByGjgT5uLFExZCvQ8sv6LK74xowK8pJH"

[programs.mainnet]
relayer = "Re1ayRHhmeqByGjgT5uLFExZCvQ8sv6LK74xowK8pJH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
# wallet = ".keys/authority.json"

[scripts]
test = "pnpm test"

[test]
startup_wait = 1000
